In [ ]:
#inbulid modules
import numpy as np
'''
  i am shashikant Giri and i stundent
'''

'\n  i am shashikant Giri and i stundent\n'

In [ ]:
!!pip install tensorflow

['Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)',
 'Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)',
 'Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)',
 'Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)',
 'Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)',
 'Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)',
 'Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)',
 'Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)',
 'Requirement already sat

In [ ]:
!!Pip install Tensorflow-tf

['/bin/bash: line 1: Pip: command not found']

In [ ]:
n_a="krit"

In [ ]:
str(23)
type(23)

int

In [ ]:
Name = input("Enter your name: ")
print("Hello " + Name )

Enter your name: krit
Hello krit


In [ ]:
a= int(input("enter first number"))
b= int(input("enter second number"))
c=a+b
print(c)

enter first number12
enter second number23
35


In [ ]:
a=23
b=34
print(a+b)

57


In [ ]:
a=23
b=34
print(a/b)

0.6764705882352942


In [ ]:
a=input("any input")
type(a)

any inputkirt


str

In [ ]:
a = 34
b = 80
c = a>b
print(c)

False


In [ ]:
a = int(input("enter first number"))
b = int(input("enter second number"))
c = a+b/2
print(c)

enter first number89
enter second number78
128.0


In [ ]:
a = int(input("enter first number "))
print(a*a)

enter first number 12
144


In [ ]:
name ="shariba"
print(name[0:])

shariba


In [ ]:
str="Bhoomi"
print(str[0:]) # Prints the full string (slicing from index 0 to end)
print(str.endswith("mi")) # Checks if the string ends with 'mi'
print(str.startswith("mi")) # Checks if the string starts with 'mi'
print(str.count("o")) # Counts the occurrences of 'o' in the string
print(str.capitalize()) # Capitalizes the first character of the string
print(str.upper()) # Converts the string to uppercase
print(str.lower()) # Converts the string to lowercase
print(str.find("h")) # Finds the index of the first occurrence of 'h'
print(str.replace("B","s")) # Replaces all occurrences of 'B' with 's'
print(str) # Prints the original string (string methods do not modify the original string in-place)

Bhoomi
True
False
2
Bhoomi
BHOOMI
bhoomi
1
shoomi
Bhoomi


In [ ]:
str="Bhoomi"
print(str.startswith("mi"))

False


In [ ]:
print("Escape sequences are crucial for formatting strings \n \t and including characters that would normally cause a syntax error \\ ")

Escape sequences are crucial for formatting strings 
 	 and including characters that would normally cause a syntax error \ 


In [ ]:
name=input("enter you name ")
print("\n Good Afternoor "+name+" well come")
str="hi  krit"
date= "31-03-2026"
letter="\nDear <|Name|>\n \t you are slected \n \t \t <|date|>"
c=letter.replace("<|Name|>","Shashikant").replace("<|date|>","31-03-2026")
print(c)
print(str.find(" "))
print(str.replace("  "," "))
print("\n Dear Shashikanr,\n \t this seminar is good,\n \t \t thanks")

enter you name krit

 Good Afternoor krit well come

Dear Shashikant
 	 you are slected 
 	 	 31-03-2026
2
hi krit

 Dear Shashikanr,
 	 this seminar is good,
 	 	 thanks


In [ ]:
list = [1,8,7,2,21,15]
list.sort()
print(list)
list.reverse()
print(list)
list.append(34)
print(list)
list.insert(3,9)
print(list)
list.remove(21)
print(list)
list.pop(3)
print(list)

[1, 2, 7, 8, 15, 21]
[21, 15, 8, 7, 2, 1]
[21, 15, 8, 7, 2, 1, 34]
[21, 15, 8, 9, 7, 2, 1, 34]
[15, 8, 9, 7, 2, 1, 34]
[15, 8, 9, 2, 1, 34]


In [ ]:
s=(1,7,12,2,2)
print(s.count(2))
print(s.index(7))

2
1


In [ ]:
furit=[]
f1=input("enter f1")
f2=input("enter f2")
f3=input("enter f3")
f4=input("enter f4")
f5=input("enter f5")
f6=input("enter f6")
f7=input("enter f7")
furit.append(f1)
furit.append(f2)
furit.append(f3)
furit.append(f4)
furit.append(f5)
furit.append(f6)
furit.append(f7)
print(furit)#q1

marks=[]
m1=int(input("enter m1"))
m2=int(input("enter m2"))
m3=int(input("enter m3"))
m4=int(input("enter m4"))
m5=int(input("enter m5"))
m6=int(input("enter m6"))
marks.append(m1)
marks.append(m2)
marks.append(m3)
marks.append(m4)
marks.append(m5)
marks.sort()
print(marks)#q2



l=[4,3,2,1]
sum=l[0]+l[1]+l[2]+l[3]
print(sum) #q4

a= (7, 0, 8, 0, 0, 9)
print(a.count(0)) #q5

enter f1mongo
enter f2apple
enter f3mongo
enter f4apple
enter f5mongo
enter f6apple
enter f7mongo
['mongo', 'apple', 'mongo', 'apple', 'mongo', 'apple', 'mongo']
enter m176
enter m245
enter m334
enter m476
enter m590
enter m643
[34, 45, 76, 76, 90]
10
3


In [ ]:
my_tuple = (1, 2, 3, 4)
print(f"Original tuple: {my_tuple}")

try:
    my_tuple[0] = 5  # Attempt to change an element
except TypeError as e:
    print(f"Attempting to modify a tuple element resulted in a TypeError: {e}")


Original tuple: (1, 2, 3, 4)
Attempting to modify a tuple element resulted in a TypeError: 'tuple' object does not support item assignment


In [ ]:
str =(1,2,4,5)
c=int(str)
print(type(c))

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

In [ ]:
a={
    'krit': 'DS&AI',
    'Nisha': 'Testing',
    'Nisha' : 'DS&AI',
    'Bhoomi' : 'GENAI'
}
print(a)

{'krit': 'DS&AI', 'Nisha': 'DS&AI', 'Bhoomi': 'GENAI'}


In [ ]:
a = {
    "key": "value",
    "sk": "code",
    "marks": "100",
    "list": [1, 2, 9, 56,78,"data", 5.98, True]
}
print(a["list"][3:6])
print(a["marks"])

[56, 78, 'data']


KeyError: 2

In [ ]:
a = {
    "key": "value",
    "code": "sk",
    "marks": "100",
    "list": [1, 2, 9, 56,78,"data", 5.98, True]
}
print(a["code"])

KeyError: 'sk'

In [ ]:
a={
    'krit': 'DS&AI',
    'Nisha': 'Testing',
    'Nisha' : 'DS&AI',
    'Bhoomi' : 'GENAI'
}
print(a.items())
print(a.keys())
print(a.values())
print(a.get("krit"))

dict_items([('krit', 'DS&AI'), ('Nisha', 'DS&AI'), ('Bhoomi', 'GENAI')])
dict_keys(['krit', 'Nisha', 'Bhoomi'])
dict_values(['DS&AI', 'DS&AI', 'GENAI'])
DS&AI


In [ ]:
a = {
    "key": "value",
    "code": "sk",
    "marks": "100",
    "list": [1, 2, 9, 56,78,"data", 5.98, True]
}
print(a.items())
print(a.keys())
print(a.values())
print(a.get("key"))
print(a.update({"key":"AI"}))
print(a)

dict_items([('key', 'value'), ('code', 'sk'), ('marks', '100'), ('list', [1, 2, 9, 56, 78, 'data', 5.98, True])])
dict_keys(['key', 'code', 'marks', 'list'])
dict_values(['value', 'sk', '100', [1, 2, 9, 56, 78, 'data', 5.98, True]])
value
None
{'key': 'AI', 'code': 'sk', 'marks': '100', 'list': [1, 2, 9, 56, 78, 'data', 5.98, True]}


In [ ]:
a= {8,5,6}
h={11,8,4,6}
print(type(a))
a.add(1)
a.add(2)
print(a)
print(len(a))
a.remove(8)
print(a)
a.pop()
print(a)
a.union(h)

<class 'set'>
{1, 2, 5, 6, 8}
5
{1, 2, 5, 6}
{2, 5, 6}


{1, 2, 4, 5, 6, 8}

In [ ]:
a= {11,8,2,3}
h={11,8,4,6}
print(a.union(h))
print(a.intersection(h))

{2, 3, 4, 6, 8, 11}
{8, 11}


In [ ]:
lan={
    "ha":"hi",
    "kay":"what",
    "nahi":"not"
}
a = input("enter a word")
print(lan[a])
print(lan.get(a))

enter a wordha
hi
hi


In [ ]:
set1= set()
v1=int(input("enter v1"))
v2=int(input("enter v2"))
v3=int(input("enter v3"))
v4=int(input("enter v4"))
v5=int(input("enter v5"))
v6=int(input("enter v6"))
v7=int(input("enter v7"))
set1.add(v1)
set1.add(v2)
set1.add(v3)
set1.add(v4)
set1.add(v1)
set1.add(v6)
set1.add(v7)
set1.add(v5)
print(set1)

enter v12
enter v26
enter v38
enter v49
{8, 9, 2, 6}


In [ ]:
s = {18,"18"}
print(s)

{18, '18'}


In [ ]:
s = set()
s.add(20)
s.add(20.0)
s.add('20')
print(s)
print(len(s))

{'20', 20}
2


In [ ]:
s ={}
print(type(s)) # we cont do typecasteing can definde in value of set anot in set.

<class 'dict'>


In [ ]:
friends ={}
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")

print(friends)

enter a langpython
enter a namekrit
enter a langC
enter a namename 2
enter a langC++
enter a namename 3
enter a langHTML
enter a namename 4
{'krit': 'python', 'name 2': 'C', 'name 3': 'C++', 'name 4': 'HTML'}


In [ ]:
friends ={}
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")
friends[input("enter a name")]= input("enter a lang")

print(friends)

enter a langc
enter a namen1
enter a langc++
enter a namen1
enter a langpython
enter a namen2
enter a langhtml
enter a namen3
{'n1': 'c++', 'n2': 'python', 'n3': 'html'}


In [ ]:
friends ={}
friends["n1"]= "c"
friends["n2"]= "c"
friends["n3"]= "java"
friends["n4"]= "python"

print(friends)

{'n1': 'c', 'n2': 'c', 'n3': 'java', 'n4': 'python'}


In [ ]:
# use ai to solve
s = {8, 7, 12, "Harry", [1,2]}
c= s[3][1].update(4)
print(s)

TypeError: unhashable type: 'list'

In [ ]:
a= int(input("enter you age"))
if a>18:
    print("you can drive")
else:
    print("you can not drive")

enter you age25
you can drive


In [ ]:
m1=40
m2=30
m3=50
if ((m1>=35) and (m2>=35) and (m3>=35)):
  print("pass")
else:
  print("fail")

fail


In [ ]:
n1=int(input("enter n1"))
n2=int(input("enter n2"))
n3=int(input("enter n3"))
n4=int(input("enter n4"))
# if((n1>n2)and(n1>n3)and(n1>n4)):
#   print(n1, "is grestest numbers")
# elif ((n2>n1)and(n2>n3)and(n2>n4)):
#   print(n2, "is grestest numbers")
# elif((n3>n1)and(n3>n2)and(n3>n4)):
#   print(n3, "is grestest numbers")
# else:
#   print(n4, "is grestest numbers")
e= max(n1,n2,n3,n4)
print(e)

enter n145
enter n232
enter n356
enter n414
56


In [ ]:
m1=float(input("enter m1"))
m2=float(input("enter m2"))
m3=float(input("enter m3"))
p1=(m1+m2+m3)/300*100
print(p1)
if((m1==p1)and(m1>=33)and(m2>=33)and(m3>=33)):
  print("pass")
else:
  print("fail")

enter m135
enter m231
enter m339
35.0
fail


In [ ]:
s= input("enter your line")
if(("Make a lot of money" in s)or("buy now" in s)or("subscribe this" in s)or("click this" in s)):
  print("spams message")
else:
  print("not spams message")

enter your linethis Make a lot of money for you
spams message


In [ ]:
a=input("enter you link")
if(len(a)>=10):
  print("more than 10 char")
else:
  print("less than 10 char")

enter you linkShashikant
more than 10 char


In [ ]:
list=["krit","Shashikant","amer","shail"]
name=input("enter you name")
if(name in list):
  print(name,"present in list")
else:
  print(name,"not present in list")

enter you namekrit
krit present in list


In [ ]:
m=int(input("enter you marks "))
if((m>=90)and(m<=100)):
  print("grade EX")
elif((m>=80)and(m<=90)):
  print("grade A")
elif((m>=70)and(m<=80)):
  print("grade B")
elif((m>=60)and(m<=70)):
  print("grade C")
elif((m>=50)and(m<=60)):
  print("grade C")
else:
  print("grade F")

enter you marks 59
grade C


In [ ]:
link= input("enter you line: ")
if("krit" in link):
  print("Krit is present in you link")
else:
  print("Krit is not present in you link")

enter you line: the krit is good friends
Krit is present in you link


In [ ]:
a=2
b=3
for i in range(1,11):
  print("2 X",i,"=",a*i ,"\t 3 X",i,"=",b*i)

2 X 1 = 2 	 3 X 1 = 3
2 X 2 = 4 	 3 X 2 = 6
2 X 3 = 6 	 3 X 3 = 9
2 X 4 = 8 	 3 X 4 = 12
2 X 5 = 10 	 3 X 5 = 15
2 X 6 = 12 	 3 X 6 = 18
2 X 7 = 14 	 3 X 7 = 21
2 X 8 = 16 	 3 X 8 = 24
2 X 9 = 18 	 3 X 9 = 27
2 X 10 = 20 	 3 X 10 = 30


In [ ]:
list =["bhoomi","sahil A","sahil B","siddhi","nisha","ankit","shraya","mahesh","mehtab","krit","anwab","Shashikant"]
for i in list:
  print("item",i)

item bhoomi
item sahil A
item sahil B
item siddhi
item nisha
item ankit
item shraya
item mahesh
item mehtab
item krit
item anwab
item Shashikant


In [ ]:
w=1
while(w<=5):
  print(w)
  w+=1

1
2
3
4
5


In [ ]:
list =["bhoomi","sahil A","sahil B","siddhi","nisha","ankit","shraya","mahesh","mehtab","krit","anwab","Shashikant"]
for i in list:
  if i=='anwab':
    continue
  print(i)


bhoomi
sahil A
sahil B
siddhi
nisha
ankit
shraya
mahesh
mehtab
krit
Shashikant


In [ ]:
a=int(input("enter you number "))
for i in range(1,11):
  print(a,"X",i,"=",a*i )

enter you number 4
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40


In [ ]:
list =["bhoomi","sahil A","sahil B","siddhi","nisha","ankit","shraya","mahesh","mehtab","krit","anwab","Shashikant"]
for i in list:
  if i.lower().startswith('s'):
    print("Well come @",i)

Well come @ sahil A
Well come @ sahil B
Well come @ siddhi
Well come @ shraya
Well come @ Shashikant


In [ ]:
a=int(input("enter you number "))
i=1
while (i<=10):
  print(a,"X",i,"=",a*i )
  i+=1

enter you number 8
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80


In [ ]:
a=int(input("enter you number "))
b=1
for i in range(1,a+1):
  b=b*i
print(b)

enter you number 10
3628800


In [ ]:
a=[]
for i in range(1,100):
  if(i%2==0):
    a.append(i)
print(a)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
a = int(input("Enter you age to check you eligiable"))
print("you are eligiable" if(a>=18) else "you are not eligiable")

Enter you age to check you eligiable20
you are eligiable


In [ ]:
a= int(input("enter you number"))
if(a>0):
  print("positive")
elif(a<0):
  print("negative")
else:
  print("zero")

enter you number-63
negative


In [ ]:
a= int(input("enter you marks "))
if(a>=35):
  if(a>75):
    print("Distinction")
  elif(a>=60):
    print("first class")
  else:
    print("just pass")
else:
  print("fail")

enter you marks35
just pass


In [ ]:
a= int(input("enter you number "))
if((a/2)or(a/3)):
  if(a/2):
    print("div by 2")
  else:
    print("div by 3")
if(a/6):
  print("div by both")
# if((a/2)and(a/3)):
#   print("div by both")

enter you number 26
div by 2
div by both


In [ ]:
li= []
no=int(input("enter you no of add item"))
for i in range(1,no+1):
  add=input("enter you item")
  li.append(add)
print("list of you amount",li)


enter you no of add item3
enter you item23
enter you item25
enter you item26
list of you amount ['23', '25', '26']


TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
total=0
while True:
  price= float(input("enter price (0 for break)"))
  if(price==0):
    break
  elif(price<0):
    continue
  else:
    total =total+price
  print(total)

enter price (0 for break)23.6
23.6
enter price (0 for break)24.1
47.7
enter price (0 for break)56.0
103.7
enter price (0 for break)0


In [ ]:
balance= 10000
while True:
  print("your balance", balance)
  amount= float(input("Enter your amount"))
  if(amount > balance):
    print("insufficient balance")
  elif(amount==0 or balance== 0):
    break
  else:
    balance=balance-amount
print("your current balance", balance)

your balance 10000
Enter your amount500
your balance 9500.0
Enter your amount1000
your balance 8500.0
Enter your amount0
your current balance 8500.0


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.array([1,5,3,2,4,6,7,8])
print(arr)
print(arr.dtype)
print(arr[3])
print(arr[1])
print(arr[1:3])
print(arr[1:8:2])
print(arr[::-1])
print(arr[5:1:-1])
print(len(arr))
print(arr+10)
print(arr-3)
print(arr*2)
print(arr%2)
print((arr+30)/2)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(arr>5)
print(arr<5)
print(arr==5)
print(arr[arr>5])
print(np.sort(a))


[ 1  2  3  4  5  6  7  8  9 10]
int64
4
2
[2 3]
[2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[6 5 4 3]
10
[11 12 13 14 15 16 17 18 19 20]
[-2 -1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18 20]
[1 0 1 0 1 0 1 0 1 0]
[15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20. ]
55
5.5
10
1
[False False False False False  True  True  True  True  True]
[ True  True  True  True False False False False False False]
[False False False False  True False False False False False]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b=np.split(a,2)
print(b)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [ ]:
b=np.array_split(arr,2)
print(b)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [ ]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
print(a*2)
print(a+2)
print("row",a[0])
print("column",a[0,1])
print("first row with second column",a[1,2])

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
row [1 2 3]
column 2
first row with second column 6


In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
# print("row wise split",np.array_split(a,3))
print("column wise split",np.array_split(a,3, axis=1))

column wise split [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [16]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[::-2])

[10  8  6  4  2]


In [42]:
ar=np.array([19,18,17,16,15])
ar1=np.array([14,13,12,11,10])
ar2=np.array([4,5,6,7,8])
print(np.concatenate((ar,ar1)))
print(ar+ar1)
print(ar*ar1)
print(ar<ar1)
print((ar*ar1)+(ar2*ar1))

[19 18 17 16 15 14 13 12 11 10]
[33 31 29 27 25]
[266 234 204 176 150]
[False False False False False]
[322 299 276 253 230]


In [44]:
a=np.array([[1,2,3],[4,5,7],[8,9,10]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a+b)

[[11 13 15]
 [17 19 22]
 [24 26 28]]


In [45]:
import pandas as pd