### **PYTHON LECTURE**

**IF ELSE STATEMENTS**

if-else ka use decision making ke liye hota hai.

Agar condition true hoti hai toh ‘if’ block execute hota hai,
aur agar condition false hoti hai toh ‘else’ block execute hota hai.

Matlab program situation ke hisaab se decision leta hai.

In [ ]:
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible")

Enter age: 45
Eligible to vote


In [ ]:
num = int(input("Enter number: "))

if num > 0:
    print("Positive number")
else:
    print("Negative number")

Enter number: 47
Positive number


**Practice Questions**

Q1) Check whether a number is even or odd

Q2) Find largest of two numbers

Q3) Check whether a person is eligible for driving license

Q4) Check whether number is positive, negative or zero

**2. NESTED IF**

Nested if ka matlab hota hai ek if ke andar dusra if.

Jab hume multiple conditions check karni hoti hain tab nested if use hota hai.

In [ ]:
num = int(input("Enter number: "))

if num > 0:
    if num % 2 == 0:
        print("Positive Even")
    else:
        print("Positive Odd")
else:
    print("Number is negative")

Enter number: 35
Positive Odd


**PRACTICE QUESTIONS:**

Q1) Voting + Gender Category

👉 Agar age ≥ 18 hai:

Agar gender = male → “Eligible Male Voter”
Agar gender = female → “Eligible Female Voter”
👉 Else → “Not eligible”

Q2) Student Result System

👉 Agar marks ≥ 35:

Check karo:
≥ 75 → Distinction
≥ 60 → First Class
Else → Pass
👉 Else:
Fail

**ELIF STATEMENT**

Elif ka full form hota hai else if

Jab hume multiple conditions check karni hoti hain, tab hum elif use karte hain.

Flow aisa hota hai:

Pehle if check hota hai
Agar wo false ho gaya, toh elif check hota hai
Agar wo bhi false ho gaya, toh next elif check hota hai
Finally else execute hota hai (agar sab false ho jaaye)

**elif ka use tab karte hain jab hume multiple options me se ek choose karna ho**

In [ ]:
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 70:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

In [ ]:
num = int(input("Enter number: "))

if (num > 0):
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

**PRACTICE QUESTIONS:**

Q1) Find largest of 3 numbers

Q2) Check grade using marks

(90+ A, 75+ B, 50+ C, else Fail)

**Q3) Check whether a number is divisible by 2, 3 or both**

**1. AND**
💬 Concept

and tab true hota hai jab dono conditions true ho

**2. OR**
💬 Concept

or tab true hota hai jab koi bhi ek condition true ho

In [ ]:
if num % 2 == 0 and num % 3 == 0:
    print("Divisible by both")

In [ ]:
if num % 2 == 0 or num % 3 == 0:
    print("Divisible by 2 or 3")

### **🔁 FOR LOOP**

for loop ka use tab hota hai jab hume pata hota hai ki loop kitni baar chalega.

Matlab repetition fixed hota hai.

For loop generally sequence ya range ke upar iterate karta hai.

In [ ]:
for i in range(1, 6):
    print(i)

1
2
3
4
5


In [ ]:
for i in range(11):
  print(i * 2)

0
2
4
6
8
10
12
14
16
18
20


**Practice Questions**

Q1) Print numbers from 1 to 50

Q2) Print even numbers from 1 to 100

Q3) Print table of any number

Q4) Find sum of first n numbers

Q5) Find factorial of a number

### **🔁 2. WHILE LOOP**

while loop tab use hota hai jab hume nahi pata hota loop kitni baar chalega.

Ye tab tak chalta hai jab tak condition true hoti hai.

For loop me count fixed hota hai,
while loop me condition control karti hai loop ko

In [ ]:
i = 1

while i <= 5:
    print(i)
    i += 1

**Practice Questions**

Q1) Print numbers from 1 to 20

Q2) Print odd numbers up to n

Q3) Find sum of digits of a number

Q4) Take input until user enters 0

### **LOOP MANIPULATION STATEMENTS IN PYTHON**

Loop manipulation statements are used to control the flow of loops during execution.

Loop manipulation statements modify the normal execution of loops.

The **break** statement terminates the loop completely and transfers control outside the loop.

The **continue** statement skips the current iteration and proceeds with the next iteration of the loop.

The **pass** statement acts as a null operation, allowing the program to run without executing any action.

These statements provide better control and flexibility while working with loops in Python.

**1. BREAK**

break ka use loop ko turant stop karne ke liye hota hai

Jab bhi break execute hota hai, loop wahi pe terminate ho jata hai aur control loop ke bahar chala jata hai

Matlab agar condition satisfy ho gayi, toh hum loop ko beech me hi rok sakte hain

In [ ]:
for i in range(1, 10):
    if i == 5:
        break
    print(i)

In [ ]:
for i in range(1, 20):
    if i % 7 == 0:
        break
    print(i)

**🎯 Practice Questions**

Q1) Print numbers but stop when number becomes 10

Q2) Print numbers until a number divisible by 5 is found

Q3) Take input from user and stop when user enters negative number

**2. CONTINUE**

continue current iteration ko skip karta hai

Matlab jis condition pe continue aayega, us iteration ka baaki code skip ho jayega aur loop next iteration pe chala jayega”

“Loop rukta nahi hai — sirf ek step skip hota hai”

In [ ]:
for i in range(1, 10):
    if i == 5:
        continue
    print(i)

In [ ]:
for i in range(1, 21):
    if i % 2 == 0:
        continue
    print(i)

**Practice Questions**

Q1) Print numbers from 1–20 but skip multiples of 3

Q2) Print only even numbers using continue

Q3) Skip numbers divisible by 5

**3. PASS**

pass ek empty statement hai

Jab hume syntax likhna hai lekin abhi logic nahi likhna, tab hum pass use karte hain

Matlab program error nahi dega, lekin kuch kaam bhi nahi karega

In [ ]:
for i in range(5):
    if i == 3:
        pass
    print(i)

In [ ]:
for i in range(5):
    pass

**🎯 Practice Questions**

Q1) Create empty loop using pass

Q2) Use pass inside if condition

Q3) Create placeholder for future logic

### **💼 PRACTICAL / BUSINESS-STYLE QUESTIONS**

**QUESTIONS**

**🧾 1. Supermarket Billing System**

Aap ek supermarket me billing system bana rahe ho.

User baar-baar item price enter karega.

Agar user 0 enter kare → billing stop ho jaye.

**Kuch rules:**

Negative price skip karo

Total bill calculate karo

**🏧 2. ATM Withdrawal System**

User ATM se paise withdraw kar raha hai.

System bar-bar amount poochega:

Agar balance se zyada amount → reject

Agar valid hai → deduct karo

Agar user 0 enter kare → exit”

### **DEFINING & CALLING FUNCTIONS**

“Function ek reusable block of code hota hai

Matlab ek baar code likho aur use baar-baar use karo

Agar hume same kaam multiple baar karna ho, toh function use karte hain instead of repeating code”


“Jaise Excel me aap formula ek baar likhte ho aur multiple cells me use karte ho
waise hi Python me function reuse hota hai”


“Function = ek kaam ka ready-made block”

**DEFINING A FUNCTION**

Function banane ke liye hum def keyword use karte hain

In [ ]:
def greet():
    print("Hello Students")

### **CALLING A FUNCTION**

“Function tab tak run nahi hota jab tak hum usko call na karein”

In [ ]:
greet()

### **FUNCTION WITH PARAMETERS**

“Parameters ka use input dene ke liye hota hai function ke andar”

In [ ]:
def add(a, b):
    print(a + b)

add(5, 3)

Q1) Create function to print your name

Q2) Create function to add two numbers

Q3) Create function to check even/odd

Q4) Create function to find factorial

### **LIBRARIES IN PYTHON**

Libraries in Python are collections of pre-written code that you can use to perform common tasks without writing everything from scratch.

A Library contains functions and modules that we resue in our Programs

Libraries make Programming Fast,Easier and Efficient

**Examples of popular Python libraries**

1)NumPy → for numerical calculations

2)Pandas → for data analysis

3)Matplotlib → for plotting graphs

### **NUMPY==Numerical Python**

It’s a popular Python library used for:

1)Fast mathematical calculations

2)Working with arrays and matrices

3)Scientific computing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


### **DIFFERENCE BETWEEN LIST AND ARRAY**

| Feature                 | List (Python)                     | Array (NumPy)                   |
| ----------------------- | --------------------------------- | ------------------------------- |
| Definition              | Built-in data structure in Python | Provided by NumPy               |
| Performance             | Slower for large data             | Faster and optimized            |
| Operations              | Need loops for calculations       | Direct operations without loops |
| Syntax                  | Simple (`[ ]`)                    | Requires NumPy (`np.array()`)   |
| Mathematical Operations | Not directly supported            | Supported (vectorized)          |
| Use Case                | General purpose programming       | Data Science, numerical work    |
| Flexibility             | More flexible                     | Less flexible but efficient     |
| Speed                   | Slower                            | Much faster                     |


**CHECKING DATA TYPE OF ARRAY**

In [ ]:
arr = np.array([1, 2.5, 3])
print(arr)
print(arr.dtype)

[1.  2.5 3. ]
float64


In [ ]:
arr = np.array([1, 2, 3])
print(arr)
print(arr.dtype)

[1 2 3]
int64


**int64**

👉 Integer (whole number) using 64 bits (8 bytes) of memory

Examples: 1, 25, -100

64 means it can store very large integers

**float64**

👉 Decimal (floating point number) using 64 bits

Examples: 1.5, 3.14, -0.99

More precision (accurate decimal values)

**<U21**

👉 This one looks weird, but it’s simple:

U = Unicode string (text)

21 = maximum length of 21 characters

< = byte order (little-endian, usually not important for beginners)

✔️ So <U21 means:

👉 A string type that can store up to 21 characters

**ACCESSING ARRAY**

In [ ]:
arr = np.array([1, 2, 3])
print(arr)
print(arr[0])
print(arr[1])

[1 2 3]
1
2


**FINDING TOTAL LENGTH OF AN ARRAY**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(len(arr))

### **Slicing**

**1)BASIC SLICING**

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


**2)FROM START**

In [ ]:
arr[:4]

array([1, 2, 3, 4])

**3)TILL END**

In [ ]:
arr[2:]

array([3, 4, 5])

**4)4. FULL ARRAY**

In [ ]:
arr[:]

**5)WITH STEP**

In [ ]:
arr=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
arr[1:8:2]

[2, 4, 6, 8]

In [ ]:
array=np.array([20,40,60,80,100,140,160])

**6)REVERSE ARRAY**

In [ ]:
array[::-1]

array([160, 140, 100,  80,  60,  40,  20])

**7)REVERSE PART**

In [ ]:
array[4:1:-1]

array([100,  80,  60])

### **BASIC OPERATIONS IN NUMPY(ARRAYS)**

**1)Addition**--->Adds 5 to all elements


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12])

**2)Subtraction**

In [ ]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5])

**3)Multiplication**

In [ ]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr1 * arr2

**4)Division**

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

**5)Power**

In [ ]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49])

**6)Modulus**

In [ ]:
arr % 2

array([1, 0, 1, 0, 1, 0, 1])

### **AGGREGATE FUNCTIONS**

**1)SUM**

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
np.sum(arr)

np.int64(28)

**2)Mean/(Avg)**

In [ ]:
np.mean(arr)

np.float64(4.0)

**3)MAX**

In [ ]:
np.max(arr)

np.int64(7)

**4)MIN**

In [ ]:
np.min(arr)

np.int64(1)

**COMPARISION OPERATORS**

**1)GREATER THAN**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,12,13,14])

arr > 10


array([False, False, False, False, False, False, False,  True,  True,
        True])

**2)EQUAL TOO**

In [ ]:
arr == 5

array([False, False, False, False,  True, False, False, False, False,
       False])

**3)LESS THAN EQUAL TOO**

In [ ]:
arr <=20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### **CONCEPTS OF SORTING AND FILTERING IN ARRAYS**

**1)Filtering:(BOOLEAN INDEXING)**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])

arr > 6

array([False, False, False, False, False, False,  True,  True,  True])

In [ ]:
arr[arr > 6]

array([7, 8, 9])

**2)Sorting Array:**

In [ ]:
arr = np.array([5, 2, 8, 1])

sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 5 8]


**SPLITTING ARRAY:**

**1)EQUAL PARTS:**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

result = np.split(arr, 2)
print(result)

[array([10, 20]), array([30, 40])]


**2)NON EQUAL PARTS:**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

result = np.array_split(arr, 3)
print(result)

[array([10, 20]), array([30, 40]), array([50])]


### **MULTI-DIMENSIONAL ARRAYS**

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 5],[7,8,9]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

**OPERATIONS ON THESE ARRAYS:**

In [ ]:
arr * 2

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [14, 16, 18]])

In [ ]:
arr + 10

array([[11, 12, 13],
       [13, 14, 15],
       [17, 18, 19]])

### **ARRAY SHAPE & SIZE**

**arr.shape (Structure / Dimensions)**

It tells you the number of rows and columns (i.e., the shape of the array)

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 5]])

arr.shape

(2, 3)

**arr.size (Total elements)**

It tells you the total number of elements in the array

In [ ]:
arr.size

9

**2D ARRAY SLICING**

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

**A)Row slicing**

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[1]

array([3, 4, 5])

**B)Column slicing**

In [ ]:
arr[:, 1]

array([2, 4])

**C)FIRST ROW, SECOND COLUMN**

In [ ]:
arr[1, 2]

np.int64(5)

### **SPLITTING 2D ARRAY**

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

**1)ROW WISE SPLIT**

In [ ]:
np.array_split(arr, 3)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

**2)Column wise Split:**

In [ ]:
np.array_split(arr, 2, axis=1)  #axis=0 for rows, axis=1 for columns

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]